## 参考文档

1. 收盘前逆回股
https://www.xuntou.net/forum.php?mod=viewthread&tid=192&extra=&user_code=3GficF

2. 常见问题
https://www.xuntou.net/forum.php?mod=viewthread&tid=66&extra=page%3D1&user_code=3GficF

3. 如何删除本地数据

https://www.xuntou.net/forum.php?mod=viewthread&tid=185&extra=page%3D1&user_code=3GficF

4. qmt 封装

https://mp.weixin.qq.com/s/EFEBtmT9uy8MLG-Nca_apw

5. 复权计算
https://www.xuntou.net/forum.php?mod=viewthread&tid=198&extra=&user_code=3GficF

## 获取数据

In [1]:
from pyqmt.dal import init_dal
import os
import cfg4py
os.environ[cfg4py.envar] = "DEV"

init_dal()

ModuleNotFoundError: No module named 'pyqmt'

In [2]:
from xtquant import xtdata as xt

xt.download_etf_info()

***** xtdata连接成功 2025-12-16 10:12:43*****
服务信息: {'tag': 'sp3', 'version': '1.0'}
服务地址: 127.0.0.1:58610
数据路径: C:\apps\qmt\bin.x64/../userdata_mini/datadir
设置xtdata.enable_hello = False可隐藏此消息

RuntimeError: 当前客户端未支持此功能，请更新客户端或升级投研版 func:commonControl, error:{ "error" : { "ErrorID" : 300000, "ErrorMsg" : "function not realize" } }

In [5]:
from xtquant import xtdata
stocks = ['000001.SZ', '600000.SH']

xtdata.download_history_data(stocks[0], '1d')
xtdata.download_history_data(stocks[1], '1d')

end = "20050104"
bars = xtdata.get_market_data(stock_list=stocks, period='1d', start_time=end, count=-1, dividend_type="front_ratio")

display(bars['close'].T.tail())

          000001.SZ  600000.SH
20251210      11.33      11.28
20251211      11.37      11.44
20251212      11.35      11.61
20251215      11.51      11.66
20251216      11.51      11.53

In [6]:
from xtquant import xtdata
stocks=['000001.SZ']
ret = xtdata.download_history_data2(stocks, '1w', '20050104', '20240315')

In [17]:

xtdata.get_market_data_ex([], stocks, '1w', start_time="20050104", end_time="20240315")

RuntimeError: 褰撳墠瀹㈡埛绔湭鏀寔姝ゅ姛鑳斤紝璇锋洿鏂板鎴风鎴栧崌绾ф姇鐮旂増

In [7]:
import datetime

now = datetime.datetime.now()
print(now.strftime("%Y%m%d%H%M%S"))

import arrow
arrow.get(now).format("YYYYMMDDHHmmss")

20251216104818

ModuleNotFoundError: No module named 'arrow'

In [8]:
from xtquant.xtdata import *

stocks = ['000001.SZ', '600000.SH']

download_history_data(stocks[0], 'tick', start_time="20230604", incrementally=True)
download_history_data(stocks[1], 'tick',start_time="20230604", incrementally=True)

In [ ]:
end = "20231206"
bars = get_market_data(stock_list=stocks, period='tick', end_time=end)

In [ ]:
bars['000001.SZ']

In [ ]:
get_market_data?

In [ ]:
import xtquant.xtdata as xt

def on_subscribe_callback(data):
    '''补充历史数据回调函数'''
    if "000001.SZ" in data:
        print(data["000001.SZ"])
    
def subcribe_live():
    xt.subscribe_whole_quote(["SH", "SZ"], on_subscribe_callback)

stock_list = ['603909.SH','300450.SZ','600740.SH', '000001.SZ']
field_list = ['time','open','close','low','high','volume']

xt.download_history_data2(stock_list, period='1d', start_time='20230201', end_time='')

# print('download_history_data2 finished')

subcribe_live()

# 获取股票close数据
import time
for i in range(10):
    time.sleep(60)
    ret = xt.get_market_data_ex(field_list, ["000001.SZ"], period='1m', start_time='', end_time='', count=1, dividend_type='front', fill_data=True)
    print(ret)

{'time': 1765853331000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 349812800.0, 'volume': 304302, 'pvolume': 30430201, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [609, 1014, 4919, 8508, 12464], 'bidVol': [847, 1313, 4158, 4533, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853334000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 349812800.0, 'volume': 304302, 'pvolume': 30430201, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [610, 1025, 4879, 8508, 12464], 'bidVol': [1508, 1304, 4158, 4533, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853337000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 349813900.0, 'volume': 304303, 'pvolume': 30430301, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [620, 1025, 4879, 8508, 12464], 'bidVol': [1508, 1304, 4158, 4533, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853340000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 349824300.0, 'volume': 304312, 'pvolume': 30431201, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [611, 1112, 4875, 8508, 12464], 'bidVol': [1508, 1304, 4158, 4533, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853343000, 'lastPrice': 11.49, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 349931200.0, 'volume': 304405, 'pvolume': 30440501, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [539, 1100, 4875, 8508, 12464], 'bidVol': [1530, 1291, 4158, 4533, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853346000, 'lastPrice': 11.49, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 349995500.0, 'volume': 304461, 'pvolume': 30446101, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [539, 1100, 4875, 8508, 12564], 'bidVol': [1474, 1291, 4158, 4503, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853349000, 'lastPrice': 11.49, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 349997800.0, 'volume': 304463, 'pvolume': 30446301, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [542, 1100, 4875, 8508, 12564], 'bidVol': [1460, 1291, 4158, 4503, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853352000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350020800.0, 'volume': 304483, 'pvolume': 30448301, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [528, 1110, 4875, 8508, 12564], 'bidVol': [806, 1291, 4158, 4503, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853355000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350054200.0, 'volume': 304512, 'pvolume': 30451201, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [500, 1110, 4885, 8508, 12564], 'bidVol': [806, 1291, 4158, 4593, 11365], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853358000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350056500.0, 'volume': 304514, 'pvolume': 30451401, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [508, 1110, 4885, 8508, 12564], 'bidVol': [846, 1291, 4158, 4593, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853361000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350056500.0, 'volume': 304514, 'pvolume': 30451401, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [510, 1110, 4885, 8518, 12564], 'bidVol': [866, 1291, 4158, 4643, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853364000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350056500.0, 'volume': 304514, 'pvolume': 30451401, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [615, 1110, 4915, 7518, 12564], 'bidVol': [966, 1291, 4160, 4643, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853367000, 'lastPrice': 11.49, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350292000.0, 'volume': 304719, 'pvolume': 30471901, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [611, 1110, 4915, 7518, 12564], 'bidVol': [774, 1291, 4160, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853370000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350301200.0, 'volume': 304727, 'pvolume': 30472701, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [643, 1110, 4943, 7518, 12564], 'bidVol': [1419, 1291, 4160, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853373000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350319600.0, 'volume': 304743, 'pvolume': 30474301, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [627, 1416, 4942, 7518, 12564], 'bidVol': [1419, 1291, 4160, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853376000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350323100.0, 'volume': 304746, 'pvolume': 30474601, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [626, 1416, 4942, 7518, 12564], 'bidVol': [771, 1290, 4160, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853379000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350670100.0, 'volume': 305048, 'pvolume': 30504801, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [774, 1416, 4942, 7518, 12564], 'bidVol': [479, 1290, 4160, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853382000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350680400.0, 'volume': 305057, 'pvolume': 30505701, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [787, 1416, 4942, 7518, 12564], 'bidVol': [471, 1290, 4129, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853385000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350681600.0, 'volume': 305058, 'pvolume': 30505801, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [786, 1416, 4942, 7518, 12564], 'bidVol': [473, 1290, 4129, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853388000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350681600.0, 'volume': 305058, 'pvolume': 30505801, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1388, 1416, 4942, 7523, 12564], 'bidVol': [656, 1290, 4129, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853391000, 'lastPrice': 11.49, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350721800.0, 'volume': 305093, 'pvolume': 30509301, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1411, 1416, 4942, 7523, 12564], 'bidVol': [630, 1290, 4129, 4653, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'000001.SZ': Empty DataFrame
Columns: [time, open, high, low, close, volume]
Index: []}
{'time': 1765853394000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350734400.0, 'volume': 305104, 'pvolume': 30510401, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1416, 1436, 4942, 7523, 12564], 'bidVol': [580, 1290, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853397000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350779200.0, 'volume': 305143, 'pvolume': 30514301, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1454, 1436, 4942, 7523, 12564], 'bidVol': [545, 1290, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853400000, 'lastPrice': 11.49, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350793000.0, 'volume': 305155, 'pvolume': 30515501, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1476, 1436, 4940, 7523, 12564], 'bidVol': [536, 1290, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853403000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350813700.0, 'volume': 305173, 'pvolume': 30517301, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1469, 1436, 4940, 7523, 12564], 'bidVol': [535, 1292, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853406000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350832100.0, 'volume': 305189, 'pvolume': 30518901, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1474, 1447, 4940, 7523, 12564], 'bidVol': [524, 1292, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853409000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350877000.0, 'volume': 305228, 'pvolume': 30522801, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1440, 1447, 4940, 7523, 12564], 'bidVol': [522, 1295, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853412000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350897700.0, 'volume': 305246, 'pvolume': 30524601, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1480, 1447, 5140, 7523, 12564], 'bidVol': [528, 1295, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853415000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350901100.0, 'volume': 305249, 'pvolume': 30524901, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1490, 1447, 5140, 7523, 12564], 'bidVol': [537, 1303, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853418000, 'lastPrice': 11.49, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350926400.0, 'volume': 305271, 'pvolume': 30527101, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1475, 1447, 5150, 7523, 12564], 'bidVol': [534, 1323, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853421000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350955100.0, 'volume': 305296, 'pvolume': 30529601, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1481, 1451, 5150, 7523, 12564], 'bidVol': [511, 1323, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853424000, 'lastPrice': 11.49, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350970100.0, 'volume': 305309, 'pvolume': 30530901, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [2060, 1451, 5165, 7523, 12564], 'bidVol': [546, 1323, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853427000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350973500.0, 'volume': 305312, 'pvolume': 30531201, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1928, 1453, 5165, 7523, 12564], 'bidVol': [593, 1323, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853430000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350982700.0, 'volume': 305320, 'pvolume': 30532001, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1924, 1453, 5165, 7523, 12564], 'bidVol': [595, 1324, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
{'time': 1765853433000, 'lastPrice': 11.5, 'open': 11.49, 'high': 11.55, 'low': 11.450000000000001, 'lastClose': 11.51, 'amount': 350985000.0, 'volume': 305322, 'pvolume': 30532201, 'stockStatus': 3, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 11.51, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [11.5, 11.51, 11.52, 11.53, 11.540000000000001], 'bidPrice': [11.49, 11.48, 11.47, 11.46, 11.450000000000001], 'askVol': [1928, 1503, 5165, 7493, 12564], 'bidVol': [596, 1324, 4129, 4683, 11303], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}

In [ ]:
import xtquant.xtdata as xt
import datetime

def on_subscribe_callback(data):
    '''补充历史数据回调函数'''
    if "000001.SZ" in data:
        print(data["000001.SZ"])
    
def subcribe_live():
    xt.subscribe_whole_quote(["SH", "SZ", "BJ"], on_subscribe_callback)

stock_list = ['000008.SZ']
field_list = ['time','open','close','low','high','volume']

start = datetime.datetime(2024, 3, 12, 9, 34)
# start_ = start.strftime("%Y%m%d%H%M")
# print(start_)
start_ = "202403121449"
xt.download_history_data2(stock_list, period='1m',start_time=start_, end_time='',callback=lambda x: print(x))

# print('download_history_data2 finished')

# subcribe_live()

# 获取股票close数据
# import time
# for i in range(3):
#     time.sleep(60)
#     ret = xt.get_market_data_ex(field_list, ["000001.SZ"], period='1m', start_time='', end_time='', count=1, dividend_type='front', fill_data=True)
#     print(ret)

xt.get_market_data_ex(field_list, ["000008.SZ"], period='1m', start_time=start_, end_time=end, count=10, dividend_type='front', fill_data=True)

***** xtdata连接成功 2025-12-16 10:22:53*****
服务信息: {'tag': 'sp3', 'version': '1.0'}
服务地址: 127.0.0.1:58610
数据路径: C:\apps\qmt\bin.x64/../userdata_mini/datadir
设置xtdata.enable_hello = False可隐藏此消息

In [17]:
import numpy as np
import datetime
np.datetime64(1710226620000, 'ms').astype(datetime.datetime)

datetime.datetime(2024, 3, 12, 6, 57)

In [75]:
import pandas as pd
import datetime
import numpy as np

df = pd.concat(ret.values(),ignore_index=True)
df.index=ret.keys()
df.time = np.array(df.time, dtype='datetime64[ms]').astype(datetime.datetime)
df.time = df["time"].dt.tz_localize('UTC').dt.tz_convert("Asia/Shanghai")

df

,time,open,high,low,close,volume,amount,suspendFlag
000001.SZ,2024-01-15 14:59:00+08:00,9.22,9.22,9.22,9.22,0,0.0,0
000004.SZ,2024-01-15 14:59:00+08:00,NaN,NaN,NaN,NaN,0,0.0,1

In [6]:
import numpy as np
import datetime

print(np.datetime64(1710127197000, 'ms').astype(datetime.datetime))
np.datetime64(1710127200000, 'ms').astype(datetime.datetime)

2024-03-11 03:19:57

datetime.datetime(2024, 3, 11, 3, 20)

## 除权数据

In [9]:
code = "000001.SZ"
dr = xtdata.get_divid_factors(code, start_time='20050104', end_time='')
dr.iloc[[1,2,-1]].drop("time", axis=1)

,interest,stockBonus,stockGift,allotNum,allotPrice,gugai,dr
20121019,0.100,0.0,0.0,0.0,0.0,0.0,1.007457
20130620,0.170,0.6,0.0,0.0,0.0,0.0,1.614093
20230614,0.285,0.0,0.0,0.0,0.0,0.0,1.025261

In [10]:
#coding:utf-8

import numpy as np
import pandas as pd

from xtquant import xtdata


def gen_divid_ratio(quote_datas, divid_datas):
    drl = []
    dr = 1.0
    qi = 0
    qdl = len(quote_datas)
    di = 0
    ddl = len(divid_datas)
    while qi < qdl and di < ddl:
        qd = quote_datas.iloc[qi]
        dd = divid_datas.iloc[di]
        if qd.name >= dd.name:
            dr *= dd['dr']
            di += 1
        if qd.name <= dd.name:
            drl.append(dr)
            qi += 1
    while qi < qdl:
        drl.append(dr)
        qi += 1
    return pd.DataFrame(drl, index = quote_datas.index, columns = quote_datas.columns)

def process_forward_ratio(quote_datas, divid_datas):
    drl = gen_divid_ratio(quote_datas, divid_datas)
    drlf = drl / drl.iloc[-1]
    result = (quote_datas * drlf).apply(lambda x: round(x, 2))
    return result

def process_backward_ratio(quote_datas, divid_datas):
    drl = gen_divid_ratio(quote_datas, divid_datas)
    result = (quote_datas * drl).apply(lambda x: round(x, 2))
    return result

def process_forward(quote_datas1, divid_datas):
    quote_datas = quote_datas1.copy()
    def calc_front(v, d):
        return round(
            (v - d['interest'] + d['allotPrice'] * d['allotNum'])
            / (1 + d['allotNum'] + d['stockBonus'] + d['stockGift'])
            , 2
        )
    for qi in range(len(quote_datas)):
        q = quote_datas.iloc[qi]
        for di in range(len(divid_datas)):
            d = divid_datas.iloc[di]
            if d.name <= q.name:
                continue
            q.iloc[0] = calc_front(q.iloc[0], d)
    return quote_datas

def process_backward(quote_datas1, divid_datas):
    quote_datas = quote_datas1.copy()
    def calc_front(v, d):
        return round(
            (v * (1 + d['stockGift'] + d['stockBonus'] + d['allotNum'])
            + d['interest'] - d['allotNum'] * d['allotPrice'])
            , 2
        )
    for qi in range(len(quote_datas)):
        q = quote_datas.iloc[qi]
        for di in range(len(divid_datas)):
            d = divid_datas.iloc[di]
            if d.name > q.name:
                continue
            q.iloc[0] = calc_front(q.iloc[0], d)
    return quote_datas


#--------------------------------

s = '000002.SZ'

xtdata.download_history_data(s, '1d')

dd = xtdata.get_divid_factors(s, start_time="20050104")
# print(dd)

#复权计算用于处理价格字段
field_list = ['open', 'high', 'low', 'close']
datas_ori = xtdata.get_market_data(field_list, [s], '1d', dividend_type = 'none', start_time='20050104', end_time='20240308')['close'].T
#print(datas_ori)


# #等比前复权
# datas_forward_ratio = process_forward_ratio(datas_ori, dd)
# print('datas_forward_ratio', datas_forward_ratio)

# #等比后复权
# datas_backward_ratio = process_backward_ratio(datas_ori, dd)
# print('datas_backward_ratio', datas_backward_ratio)

# #前复权
# datas_forward = process_forward(datas_ori, dd)
# print('datas_forward', datas_forward)

# #后复权
# datas_backward = process_backward(datas_ori, dd)
# print('datas_backward', datas_backward)

pd.options.display.max_rows = 500
%timeit factors = gen_divid_ratio(datas_ori, dd)

                  time  interest  stockBonus  stockGift  allotNum  allotPrice  \
20050629  1.119974e+12  0.150000         0.0        0.5       0.0         0.0
20060721  1.153411e+12  0.150000         0.0        0.0       0.0         0.0
20070516  1.179245e+12  0.150000         0.0        0.5       0.0         0.0
20080616  1.213546e+12  0.100000         0.0        0.6       0.0         0.0
20090608  1.244390e+12  0.050000         0.0        0.0       0.0         0.0
20100518  1.274112e+12  0.070000         0.0        0.0       0.0         0.0
20110527  1.306426e+12  0.100000         0.0        0.0       0.0         0.0
20120705  1.341418e+12  0.130000         0.0        0.0       0.0         0.0
20130516  1.368634e+12  0.180000         0.0        0.0       0.0         0.0
20140508  1.399478e+12  0.410000         0.0        0.0       0.0         0.0
20150721  1.437408e+12  0.500000         0.0        0.0       0.0         0.0
20160729  1.469722e+12  0.720000         0.0        0.0       0.0         0.0
20170829  1.503936e+12  0.790000         0.0        0.0       0.0         0.0
20180823  1.534954e+12  0.900000         0.0        0.0       0.0         0.0
20190815  1.565798e+12  1.045102         0.0        0.0       0.0         0.0
20200814  1.597334e+12  1.016613         0.0        0.0       0.0         0.0
20210825  1.629821e+12  1.250000         0.0        0.0       0.0         0.0
20220825  1.661357e+12  0.968802         0.0        0.0       0.0         0.0
20230825  1.692893e+12  0.674898         0.0        0.0       0.0         0.0

          gugai        dr
20050629    0.0  1.545731
20060721    0.0  1.025295
20070516    0.0  1.510190
20080616    0.0  1.609756
20090608    0.0  1.004699
20100518    0.0  1.010218
20110527    0.0  1.012820
20120705    0.0  1.014476
20130516    0.0  1.016172
20140508    0.0  1.054959
20150721    0.0  1.033670
20160729    0.0  1.041860
20170829    0.0  1.034022
20180823    0.0  1.039096
20190815    0.0  1.040260
20200814    0.0  1.036983
20210825    0.0  1.057418
20220825    0.0  1.061980
20230825    0.0  1.051380
407 ms ± 14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [15]:
import datetime
def calc_factors(code, end: datetime.date):
    pass

# diff_factors = xtdata.get_divid_factors("000001.SZ")
diff_factors.index[0]

'19910403'

In [19]:
# init cache

from pyqmt.dal import init_dal
import os
import cfg4py
os.environ[cfg4py.envar] = "DEV"
init_dal()

cfg = cfg4py.get_instance()

2024-03-08 21:19:55,935 I cfg4py.core:update_config:280 | configuration is
chores_db_path: d:\data\pyqmt.db
clickhouse: {database: zillionare, host: 192.168.100.10, password: 123456, user: default}
redis: {host: 192.168.100.10, port: 6379}
server: {prefix: pyqmt}

In [20]:
now = datetime.datetime.now()

'2024'

## 如果数据没有缓存，则get_market_data会失败

In [ ]:
ret = get_market_data(field_list, ['000004.SZ'], period='1d', start_time='', count=5, dividend_type='front', fill_data=True)

print(ret['close'].T)
print(ret)

In [ ]:
import pandas as pd
import datetime
from xtquant import xtdata

def get_tick(code, start_time, end_time, period='tick'):
    xtdata.download_history_data(code, period=period, start_time=start_time, end_time=end_time)
    data = xtdata.get_local_data(field_list=[], stock_list=[code], period=period, count=10)
    result_list = data[code]
    df = pd.DataFrame(result_list)

    df['time_str'] = df['time'].apply(lambda x: datetime.datetime.fromtimestamp(x / 1000.0))
    return df


def process_timestamp(df, filename):
    df = df.set_index('time_str')
    result = df.resample('3S').first().ffill()
    # result = result[(result.index >= '2022-07-20 09:30') & (result.index <= '2022-07-20 15:00')]
    result = result.reset_index()
    result.to_csv(filename + '.csv')


def dump_single_code_tick():
    # 导出单个转债的tick数据
    code='128022'
    start_date = '20210113'
    end_date = '20210130'

    post_fix = 'SZ' if code.startswith('12') else 'SH'
    code = '{}.{}'.format(code,post_fix)
    df = get_tick(code, start_date, end_date)
    return df

dump_single_code_tick()

## get_full_tick

In [ ]:
from xtquant.xtdata import get_full_tick,get_divid_factors

get_full_tick(['SH'])
get_divid_factors('000001.SZ', start_time='', end_time='')

In [ ]:
from xtquant.xtdata import get_l2_quote
get_l2_quote(field_list=[], stock_code='', start_time='', end_time='', count=-1)

In [ ]:
code = '000001.SZ'
get_instrument_detail(code)

## 获取交易日历
注意返回时间是毫秒单位，如果我们用datetime.datetime来转换，需要除以1000
也可以用numpy来转换

In [ ]:
days = get_trading_dates('SH', start_time='', end_time='', count=10)
import numpy as np
np.array(days, dtype='datetime64[ms]').astype(datetime.date)

In [ ]:
get_trading_dates('SH', end_time='20230908', count=10)

### 时间戳转换函数

In [ ]:

import time
def conv_time(ct):
    '''
    conv_time(1476374400000) --> '20161014000000.000'
    '''
    local_time = time.localtime(ct / 1000)
    data_head = time.strftime('%Y%m%d%H%M%S', local_time)
    data_secs = (ct - int(ct)) * 1000
    time_stamp = '%s.%03d' % (data_head, data_secs)
    return time_stamp

conv_time(1693152000000)

In [ ]:
import time
time.time()

import datetime

datetime.datetime.fromtimestamp(1694448000)

In [ ]:
from xtquant import xtdata
sectors = xtdata.get_sector_list()
print(len(sectors))
for i in range(0, len(sectors), 6):
    print(" ".join(sectors[i:i+6]))

## 获取板块列表和成份股
析块列表没有索引，以字符串格式返回，也没有时间标签
获取板块名字后，直接通过板块名字来获取成份股

In [2]:
from xtquant import xtdata
for sector in xtdata.get_sector_list():
    if sector.find("可转债") != -1:
        print(sector)
xtdata.get_stock_list_in_sector("沪深A股")
xtdata.get_stock_list_in_sector("可转债等权")
xtdata.get_instrument_detail("110047.SH")

***** xtdata连接成功 *****
服务信息: None
服务地址: None
数据路径: None
设置xtdata.enable_hello = False可隐藏此消息

可转债正股等权
可转债等权

{'ExchangeID': 'SH',
 'InstrumentID': '110047',
 'InstrumentName': '山鹰转债',
 'ProductID': '',
 'ProductName': '',
 'ExchangeCode': None,
 'UniCode': None,
 'CreateDate': '0',
 'OpenDate': '20181210',
 'ExpireDate': 20241121,
 'PreClose': 109.001,
 'SettlementPrice': 109.001,
 'UpStopPrice': 130.801,
 'DownStopPrice': 87.201,
 'FloatVolume': 2246118263.0,
 'TotalVolume': 2300000000.0,
 'LongMarginRatio': 1.7976931348623157e+308,
 'ShortMarginRatio': 1.7976931348623157e+308,
 'PriceTick': 0.001,
 'VolumeMultiple': 1,
 'MainContract': 2147483647,
 'LastVolume': 2147483647,
 'InstrumentStatus': 0,
 'IsTrading': False,
 'IsRecent': False,
 'ProductTradeQuota': None,
 'ContractTradeQuota': None,
 'ProductOpenInterestQuota': None,
 'ContractOpenInterestQuota': None}

In [12]:
xtdata.get_instrument_detail("399300.SZ")

{'ExchangeID': 'SZ',
 'InstrumentID': '399300',
 'InstrumentName': '沪深300',
 'ProductID': '',
 'ProductName': '',
 'ExchangeCode': None,
 'UniCode': None,
 'CreateDate': '0',
 'OpenDate': '0',
 'ExpireDate': 99999999,
 'PreClose': 3597.4939,
 'SettlementPrice': 3597.4939,
 'UpStopPrice': 3957.243,
 'DownStopPrice': 3237.745,
 'FloatVolume': 0.0,
 'TotalVolume': 0.0,
 'LongMarginRatio': 1.7976931348623157e+308,
 'ShortMarginRatio': 1.7976931348623157e+308,
 'PriceTick': 0.001,
 'VolumeMultiple': 1,
 'MainContract': 2147483647,
 'LastVolume': 2147483647,
 'InstrumentStatus': 0,
 'IsTrading': False,
 'IsRecent': False,
 'ProductTradeQuota': None,
 'ContractTradeQuota': None,
 'ProductOpenInterestQuota': None,
 'ContractOpenInterestQuota': None}

In [ ]:
index = []
for sector in xtdata.get_sector_list():
    if "迅投" in sector:
        print(sector)

for code in xtdata.get_stock_list_in_sector("迅投一级行业板块指数"):
    detail = xtdata.get_instrument_detail(code)
    name = detail["InstrumentName"]
    if name.startswith("SW"):
        print(code, name)
        


# secs = xtdata.get_stock_list_in_sector('GNoled材料')
# xtdata.download_history_data2(secs, period='1d', start_time="20231220")

# barss = xtdata.get_market_data(stock_list=secs, count=10)
# barss["close"]

In [ ]:
xtdata.get_instrument_detail("SW1电力设备")

In [ ]:
from collections import defaultdict

sectors = defaultdict(list)
prefixes = [
    '1000SW', '500SW', '300SW', 'CSRC', 
    '迅投一级', '迅投二级', '迅投三级', 
    'HKSW', 'TGN', 'TDY', 'THY', 'DY1', 
    'DY2', 'SW1', 'SW2', 'SW3', 'ETF',
    'GN', '转债', '国证', '上证', '沪深', 
    '中证','深证'
]

download_sector_data()

for item in get_sector_list():
    for i in range(6, 1, -1):
        key = item[:i]

        if key in prefixes:
            sectors[key].append(item)
            break
    else:
        sectors['NA'].append(item)

for key, codes in sectors.items():
    print(key, len(codes))

### 可转债

In [ ]:
for sector in xtdata.get_sector_list():
    if sector.find("可转债") != -1:
        print(sector)

convertibles = xtdata.get_stock_list_in_sector("可转债等权")
instrument = xtdata.get_instrument_detail(convertibles[0])
exg = instrument["ExchangeID"]
_id = instrument["InstrumentID"]
name = instrument["InstrumentName"]

print(_id + exg, name)

In [ ]:
print(len(xtdata.get_stock_list_in_sector('沪深指数')))
for sector in xtdata.get_stock_list_in_sector('沪深指数'):
    detail = xtdata.get_instrument_detail(sector)
    name = detail["InstrumentName"]
    if name == "中证1000":
        print(sector)

xtdata.download_history_data("399852.SZ", period="1d")
xtdata.get_market_data(stock_list=["000050.SH"], period='1d', count=10)

In [ ]:
xtdata.get_market_data(stock_list=[sector])

## 获取指数列表及指数行情

In [ ]:
xtdata.get_stock_list_in_sector("沪深指数")
xtdata.get_instrument_type("000100.SH")
xtdata.get_instrument_detail("000100.SH")

xtdata.download_history_data("000100.SH", '1d')
xtdata.get_market_data(stock_list=["000100.SH"], period="1d")

## 获取历史涨跌停数据

In [43]:
from xtquant import xtdata
xtdata.download_history_data(stock_code="600000.SH", period="stoppricedata")

RuntimeError: 褰撳墠瀹㈡埛绔湭鏀寔姝ゅ姛鑳斤紝璇锋洿鏂板鎴风鎴栧崌绾ф姇鐮旂増

In [ ]:
download_sector_data()

In [ ]:
len(get_stock_list_in_sector('沪深A股'))

In [ ]:
from collections import defaultdict
from xtquant.xtdata import *

sectors = defaultdict(list)
prefixes = [
    '1000SW', '500SW', '300SW', 'CSRC', '迅投一级', '迅投二级', '迅投三级', 'HKSW',
'TGN', 'TDY', 'THY', 'DY1', 'DY2', 'SW1', 'SW2', 'SW3', 'ETF','GN', '转债', '国证', '上证', '沪深', '中证','深证'
]

sectors = set()

for item in get_sector_list():
    for i in range(6, 1, -1):
        key = item[:i]

        if key.startswith("SW1"):
            sectors.add(key)
            break


print(sectors)
# all_stocks = get_stock_list_in_sector('沪深A股')
# print(f"当前共计{len(all_stocks)}股A股")
# print(all_stocks[:5])

In [ ]:
xt.get_stock_list_in_sector("SW1煤炭")

# coding=utf-8
from xtquant import xtdata
# 下载权重相关信息
xtdata.download_index_weight()
# 获取权重相关信息
xtdata.get_index_weight('SW1煤炭')

In [ ]:
from xtquant.xtdata import get_instrument_detail
get_instrument_detail('000001.SZ')

In [ ]:
#coding=utf-8
from xtquant.xttrader import XtQuantTrader, XtQuantTraderCallback
from xtquant.xttype import StockAccount
from xtquant import xtconstant
import numpy as np


class MyXtQuantTraderCallback(XtQuantTraderCallback):
    def on_disconnected(self):
        """
        连接断开
        :return:
        """
        print("connection lost")

    def on_stock_order(self, order):
        """
        委托回报推送
        :param order: XtOrder对象
        :return:
        """
        print("on order callback:")
        print(order.stock_code, order.order_status, order.order_sysid)
 
    def on_stock_trade(self, trade):
        """
        成交变动推送
        :param trade: XtTrade对象
        :return:
        """
        print("on trade callback")
        print(trade.account_id, trade.stock_code, trade.order_id)

    def on_stock_position(self, position):
        """
        持仓变动推送  注意，该回调函数目前不生效
        :param position: XtPosition对象
        :return:
        """
        print("on position callback")
        print(position.stock_code, position.volume)

    def on_order_error(self, order_error):
        """
        委托失败推送
        :param order_error:XtOrderError 对象
        :return:
        """
        print("on order_error callback")
        print(order_error.order_id, order_error.error_id, order_error.error_msg)

    def on_cancel_error(self, cancel_error):
        """
        撤单失败推送
        :param cancel_error: XtCancelError 对象
        :return:
        """
        print("on cancel_error callback")
        print(cancel_error.order_id, cancel_error.error_id, cancel_error.error_msg)

    def on_order_stock_async_response(self, response):
        """
        异步下单回报推送
        :param response: XtOrderResponse 对象
        :return:
        """
        print("on_order_stock_async_response")
        print(response.account_id, response.order_id, response.seq)

    def on_account_status(self, status):
        """
        :param response: XtAccountStatus 对象
        :return:
        """
        print("on_account_status")
        print(status.account_id, status.account_type, status.status)

# path为mini qmt客户端安装目录下userdata_mini路径
path = 'D:\\国金QMT交易端模拟\\userdata_mini'
session_id = np.random.randint(20000, 60000)
xt_trader = XtQuantTrader(path, session_id)

# path为mini qmt客户端安装目录下userdata_mini路径
path = 'D:\\国金QMT交易端模拟\\userdata_mini'

session_id = np.random.randint(20000, 60000)
xt_trader = XtQuantTrader(path, session_id)

# 创建交易回调类对象，并声明接收回调
callback = MyXtQuantTraderCallback()
xt_trader.register_callback(callback)

# 启动交易线程
xt_trader.start()
# 建立交易连接，返回0表示连接成功
connect_result = xt_trader.connect()
assert connect_result == 0

acc = StockAccount('55010149', 'STOCK')
# 对交易回调进行订阅，订阅后可以收到交易主推，返回0表示订阅成功
subscribe_result = xt_trader.subscribe(acc)
assert subscribe_result == 0

In [ ]:

stock_code = '600000.SH'
# 使用指定价下单，接口返回订单编号，后续可以用于撤单操作以及查询委托状态
print("order using the fix price:")
fix_result_order_id = xt_trader.order_stock(acc, stock_code, xtconstant.STOCK_BUY, 200, xtconstant.FIX_PRICE, 10.5, 'strategy_name', 'remark')
print(fix_result_order_id)

# 使用订单编号撤单
print("cancel order:")
cancel_order_result = xt_trader.cancel_order_stock(acc, fix_result_order_id)
print(cancel_order_result)

# 使用异步下单接口，接口返回下单请求序号seq，seq可以和on_order_stock_async_response的委托反馈response对应起来
print("order using async api:")
async_seq = xt_trader.order_stock_async(acc, stock_code, xtconstant.STOCK_BUY, 200, xtconstant.FIX_PRICE, 10.5, 'strategy_name', 'remark')
print(async_seq)

# 查询证券资产
print("query asset:")
asset = xt_trader.query_stock_asset(acc)
if asset:
    print("asset:")
    print("cash {0}".format(asset.cash))

# 根据订单编号查询委托
print("query order:")
order = xt_trader.query_stock_order(acc, fix_result_order_id)
if order:
    print("order:")
    print("order {0}".format(order.order_id))

    # 阻塞线程，接收交易推送
    # xt_trader.run_forever()

In [ ]:
xt_trader.order_stock?

In [ ]:
import akshare

akshare.stock_hot_rank_detail_realtime_em("SZ000665")

## ST

In [ ]:
from xtquant import xtdata
xtdata.download_his_st_data()
xtdata.get_his_st_data("000564.SZ")

In [45]:

from xtquant import xtdata
import time


def my_download(stock_list,period,start_date = '', end_date = ''):
  '''
  用于显示下载进度
  '''
  if "d" in period:
    period = "1d"
  elif "m" in period:
    if int(period[0]) < 5:
      period = "1m"
    else:
      period = "5m"
  elif "tick" == period:
    pass
  else:
    raise KeyboardInterrupt("周期传入错误")


  n = 1
  num = len(stock_list)
  for i in stock_list:
    print(f"当前正在下载{n}/{num}")
    
    xtdata.download_history_data(i,period,start_date, end_date)
    n += 1
  print("下载任务结束")

def do_subscribe_quote(stock_list:list, period:str):
  for i in stock_list:
    xtdata.subscribe_quote(i,period = period)
  time.sleep(1) # 等待订阅完成



start_date = '20231001'# 格式"YYYYMMDD"，开始下载的日期，date = ""时全量下载
end_date = "" 
period = "1d" 

need_download = 1  # 取数据是空值时，将need_download赋值为1，确保正确下载了历史数据

code_list = ["000001.SZ", "600519.SH"] # 股票列表

if need_download: # 判断要不要下载数据, gmd系列函数都是从本地读取历史数据,从服务器订阅获取最新数据
    my_download(code_list, period, start_date, end_date)

############ 仅获取历史行情 #####################
count = -1 # 设置count参数，使gmd_ex返回全部数据
data1 = xtdata.get_market_data_ex([],code_list,period = period, start_time = start_date, end_time = end_date)

############ 仅获取最新行情 #####################
do_subscribe_quote(code_list,period)# 设置订阅参数，使gmd_ex取到最新行情
count = 1 # 设置count参数，使gmd_ex仅返回最新行情数据
data2 = xtdata.get_market_data_ex([],code_list,period = period, start_time = start_date, end_time = end_date, count = 1) # count 设置为1，使返回值只包含最新行情

############ 获取历史行情+最新行情 #####################
do_subscribe_quote(code_list,period) # 设置订阅参数，使gmd_ex取到最新行情
count = -1 # 设置count参数，使gmd_ex返回全部数据
data3 = xtdata.get_market_data_ex([],code_list,period = period, start_time = start_date, end_time = end_date, count = -1) # count 设置为1，使返回值只包含最新行情


print(data1[code_list[0]].tail())# 行情数据查看
print(data2[code_list[0]].tail())
print(data3[code_list[0]].tail())

当前正在下载1/2
当前正在下载2/2
下载任务结束
                   time   open   high    low  close   volume        amount  \
20240304  1709481600000  10.45  10.50  10.32  10.33  1655930  1.719563e+09
20240305  1709568000000  10.30  10.47  10.26  10.43  1817319  1.889144e+09
20240306  1709654400000  10.40  10.45  10.33  10.33  1345640  1.396940e+09
20240307  1709740800000  10.33  10.64  10.33  10.38  2016166  2.109589e+09
20240308  1709827200000  10.35  10.44  10.30  10.38  1113974  1.154491e+09

          settelementPrice  openInterest  preClose  suspendFlag
20240304               0.0            15     10.49            0
20240305               0.0            15     10.33            0
20240306               0.0            15     10.43            0
20240307               0.0            15     10.33            0
20240308               0.0            15     10.38            0
                   time   open   high   low  close   volume        amount  \
20240308  1709827200000  10.35  10.44  10.3  10.38  1113974  1.154491e+09

          settelementPrice  openInterest  preClose  suspendFlag
20240308               0.0            15     10.38            0
                   time   open   high    low  close   volume        amount  \
20240304  1709481600000  10.45  10.50  10.32  10.33  1655930  1.719563e+09
20240305  1709568000000  10.30  10.47  10.26  10.43  1817319  1.889144e+09
20240306  1709654400000  10.40  10.45  10.33  10.33  1345640  1.396940e+09
20240307  1709740800000  10.33  10.64  10.33  10.38  2016166  2.109589e+09
20240308  1709827200000  10.35  10.44  10.30  10.38  1113974  1.154491e+09

          settelementPrice  openInterest  preClose  suspendFlag
20240304               0.0            15     10.49            0
20240305               0.0            15     10.33            0
20240306               0.0            15     10.43            0
20240307               0.0            15     10.33            0
20240308               0.0            15     10.38            0

In [12]:
data = {
    "000001.SZ": {'time': 1710127194000, 'lastPrice': 10.42, 'open': 10.38, 'high': 10.47, 'low': 10.34, 'lastClose': 10.38, 'amount': 710422600.0, 'volume': 683450, 'pvolume': 68345011, 'stockStatus': 0, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 0.0, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [10.42, 10.43, 10.44, 0.0, 0.0], 'bidPrice': [10.41, 10.4, 10.39, 0.0, 0.0], 'askVol': [9349, 7557, 6217, 0, 0], 'bidVol': [3119, 6685, 4865, 0, 0], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0},
    "000002.SZ": {'time': 1710127197000, 'lastPrice': 10.41, 'open': 10.38, 'high': 10.47, 'low': 10.34, 'lastClose': 10.38, 'amount': 710455900.0, 'volume': 683482, 'pvolume': 68348211, 'stockStatus': 0, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 0.0, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [10.42, 10.43, 10.44, 0.0, 0.0], 'bidPrice': [10.41, 10.4, 10.39, 0.0, 0.0], 'askVol': [9359, 7557, 6247, 0, 0], 'bidVol': [3133, 6685, 4865, 0, 0], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0},
    "000004.SZ": {'time': 1710127200000, 'lastPrice': 10.41, 'open': 10.38, 'high': 10.47, 'low': 10.34, 'lastClose': 10.38, 'amount': 710954600.0, 'volume': 683961, 'pvolume': 68396111, 'stockStatus': 0, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 0.0, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [10.42, 10.43, 10.44, 0.0, 0.0], 'bidPrice': [10.41, 10.4, 10.39, 0.0, 0.0], 'askVol': [9351, 7557, 6247, 0, 0], 'bidVol': [2828, 6690, 4865, 0, 0], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0},
    "000005.SZ": {'time': 1710127203000, 'lastPrice': 10.42, 'open': 10.38, 'high': 10.47, 'low': 10.34, 'lastClose': 10.38, 'amount': 710973300.0, 'volume': 683979, 'pvolume': 68397911, 'stockStatus': 0, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 0.0, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [10.42, 10.43, 10.44, 0.0, 0.0], 'bidPrice': [10.41, 10.4, 10.39, 0.0, 0.0], 'askVol': [9495, 7557, 6247, 0, 0], 'bidVol': [2831, 6711, 4865, 0, 0], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0},
    "000006.SZ": {'time': 1710127206000, 'lastPrice': 10.42, 'open': 10.38, 'high': 10.47, 'low': 10.34, 'lastClose': 10.38, 'amount': 710977500.0, 'volume': 683983, 'pvolume': 68398311, 'stockStatus': 0, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 0.0, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [10.42, 10.43, 10.44, 0.0, 0.0], 'bidPrice': [10.41, 10.4, 10.39, 0.0, 0.0], 'askVol': [9523, 7619, 6247, 0, 0], 'bidVol': [3347, 6711, 4865, 0, 0], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0},
    "000007.SZ": {'time': 1710127209000, 'lastPrice': 10.42, 'open': 10.38, 'high': 10.47, 'low': 10.34, 'lastClose': 10.38, 'amount': 711872600.0, 'volume': 684842, 'pvolume': 68484211, 'stockStatus': 0, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 0.0, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [10.42, 10.43, 10.44, 0.0, 0.0], 'bidPrice': [10.41, 10.4, 10.39, 0.0, 0.0], 'askVol': [8664, 7619, 6315, 0, 0], 'bidVol': [3405, 6701, 4865, 0, 0], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0},
    "000010.SZ": {'time': 1710127212000, 'lastPrice': 10.42, 'open': 10.38, 'high': 10.47, 'low': 10.34, 'lastClose': 10.38, 'amount': 711953800.0, 'volume': 684920, 'pvolume': 68492011, 'stockStatus': 0, 'openInt': 13, 'transactionNum': 0, 'lastSettlementPrice': 0.0, 'settlementPrice': 0.0, 'pe': 0.0, 'askPrice': [10.42, 10.43, 10.44, 0.0, 0.0], 'bidPrice': [10.41, 10.4, 10.39, 0.0, 0.0], 'askVol': [8619, 7575, 6315, 0, 0], 'bidVol': [3924, 6701, 4825, 0, 0], 'volRatio': 0.0, 'speed1Min': 0.0, 'speed5Min': 0.0}
}

In [32]:
%timeit {code: item["lastPrice"] for code, item in data.items()}

2.74 µs ± 792 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [1]:
import akshare as ak

stock_zh_a_spot_em_df = ak.stock_zh_a_spot_em()
print(stock_zh_a_spot_em_df)

        序号      代码    名称    最新价    涨跌幅   涨跌额        成交量           成交额     振幅  \
0        1  300391  长药控股   5.80  20.08  0.97    78770.0  4.435229e+07  20.50
1        2  300975  商络电子  10.48  20.05  1.75   784818.0  7.400884e+08  23.25
2        3  301390  经纬股份  39.64  20.01  6.61    27974.0  1.077989e+08  19.95
3        4  688260  昀冢科技  23.45  20.01  3.91   155242.0  3.403509e+08  17.40
4        5  301292  海科新源  20.22  20.00  3.37   183261.0  3.655377e+08   8.43
...    ...     ...   ...    ...    ...   ...        ...           ...    ...
5593  5594  301162  国能日新  51.09  -7.28 -4.01    61603.0  3.194107e+08   5.06
5594  5595  601918  新集能源   7.46  -7.79 -0.63  1071167.0  8.123016e+08   7.54
5595  5596  603131  上海沪工  16.48  -8.14 -1.46   636330.0  1.075383e+09   9.31
5596  5597  603665   康隆达  22.05  -8.88 -2.15    45968.0  1.023941e+08   7.64
5597  5598  600818  中路股份  18.76  -9.11 -1.88   587166.0  1.188852e+09  19.96

         最高  ...    量比    换手率  市盈率-动态    市净率           总市值          流通市值  \
0      5.80  ...  1.37   2.25  -13.15   2.97  2.031949e+09  2.031949e+09
1     10.48  ...  1.49  24.22  149.86   3.83  6.606682e+09  3.396595e+09
2     39.64  ...  2.25  18.65   71.79   2.59  2.378400e+09  5.946000e+08
3     23.45  ...  1.33  22.79  -23.51   8.14  2.814000e+09  1.597326e+09
4     20.22  ...  7.69  40.58   53.55   1.42  4.508315e+09  9.132204e+08
...     ...  ...   ...    ...     ...    ...           ...           ...
5593  53.56  ...  1.61  10.17   73.39   4.90  5.070666e+09  3.094006e+09
5594   8.00  ...  2.21   4.13    9.18   1.43  1.932544e+10  1.932544e+10
5595  17.99  ...  1.21  20.01   89.04   4.06  5.240466e+09  5.240466e+09
5596  23.70  ...  1.49   2.86  -88.22   2.65  3.584816e+09  3.543062e+09
5597  22.70  ...  2.68  24.68  479.07  10.62  6.030363e+09  4.464090e+09

        涨速  5分钟涨跌  60日涨跌幅  年初至今涨跌幅
0     0.00   0.00  -24.38   -25.06
1     0.00   0.00   28.59    26.72
2     0.00   0.00   -3.39    -8.89
3     0.00   0.00  -21.20   -22.61
4     0.00   0.00    3.48     3.69
...    ...    ...     ...      ...
5593 -0.02  -0.23   -0.14    -1.52
5594  0.27   0.13   43.46    41.56
5595  0.00   0.92   11.96    11.65
5596  0.00   0.23   -8.81   -27.61
5597  0.00  -1.73   46.22    56.46

[5598 rows x 23 columns]

In [4]:
stock_zh_a_spot_em_df[:10][["名称", "最新价", "成交量", "最高", "最低","今开", "昨收"]]

     名称    最新价        成交量     最高     最低     今开     昨收
0  长药控股   5.80    78770.0   5.80   4.81   4.81   4.83
1  商络电子  10.48   784818.0  10.48   8.45   8.57   8.73
2  经纬股份  39.64    27974.0  39.64  33.05  33.05  33.03
3  昀冢科技  23.45   155242.0  23.45  20.05  20.06  19.54
4  海科新源  20.22   183261.0  20.22  18.80  19.00  16.85
5  金盾股份  10.80  1041970.0  10.80   8.88   8.93   9.00
6  佐力药业  13.32   863169.0  13.32  12.83  12.98  11.10
7  建新股份   5.52   746788.0   5.52   4.42   4.57   4.60
8  星源卓镁  55.87    97478.0  55.87  45.70  46.80  46.56
9  香雪制药   4.63   487859.0   4.63   3.89   3.89   3.86